BethanysPieShopNet8/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShopNet8.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BethanysPieShopNet8/Controllers/PieController.cs
using BethanysPieShopNet8.Models;
using BethanysPieShopNet8.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShopNet8.Controllers
{
    public class PieController : Controller
    {
        // Private fields for the pie repository, category repository, and logger
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ILogger<PieController> _logger;

        // Constructor with dependency injection for IPieRepository, ICategoryRepository, and ILogger
        public PieController(IPieRepository pieRepository,
                             ICategoryRepository categoryRepository,
                             ILogger<PieController> logger)
        {
            _pieRepository = pieRepository ?? throw new ArgumentNullException(nameof(pieRepository));
            _categoryRepository = categoryRepository ?? throw new ArgumentNullException(nameof(categoryRepository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }


        // Action method for listing pies, optionally filtered by category
        public IActionResult List(string category)
        {
            _logger.LogInformation("Loading pies list...");

            IEnumerable<Pie> pies;
            string? currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
                return View(new PieListViewModel(pies, currentCategory));

            }

            pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category)
                .OrderBy(p => p.PieId);

            currentCategory = _categoryRepository.AllCategories
                .FirstOrDefault(c => c.CategoryName == category)?.CategoryName;

            return View(new PieListViewModel(pies, currentCategory));
        }

        // Action method for displaying details of a specific pie by ID
        public IActionResult Details(int id)
        {
            _logger.LogInformation("Loading pie details with ID: {id}...", id);

            var pie = _pieRepository.GetPieById(id);

            if (pie == null)
                return NotFound();

            return View(pie);
        }

        // Action method for displaying the search page
        public IActionResult Search()
        {
            return View();
        }
    }
}

BethanysPieShopNet8/Views/Shared/_FooterLayout.cshtml
<footer class="bg-light my-1">
    <div class="container py-5">
        <div class="row">
            <div class="col-sm-6 col-lg-3">
                <h6>Quick links:</h6>
                <ul class="list-unstyled">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a href="shop.html">Shop</a></li>
                    <li><a asp-controller="About" asp-action="Index">About</a></li>
                    <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                    <li><a href="wishlist.html">Wishlist</a></li>
                    <li><a asp-controller="ShoppingCart" asp-action="Index">Cart</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-lg-3">
                <h6>Information:</h6>
                <ul class="list-unstyled">
                    <li><a href="faq.html">Frequently Asked Questions</a></li>
                    <li><a href="shipping.html">Shipping</a></li>
                    <li><a href="returns.html">Returns</a></li>
                    <li><a href="terms-of-service.html">Terms of Service</a></li>
                    <li><a href="privacy-policy.html">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-lg-3">
                <h6>Follow us:</h6>
                <ul class="list-unstyled">
                    <li><i class="bi-facebook text-primary"></i> <a href="#">Facebook</a></li>
                    <li><i class="bi-instagram text-primary"></i> <a href="#">Instagram</a></li>
                    <li><i class="bi-twitter text-primary"></i> <a href="#">Twitter</a></li>
                    <li><i class="bi-youtube text-primary"></i> <a href="#">YouTube</a></li>
                    <li><i class="bi-linkedin text-primary"></i> <a href="#">LinkedIn</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-lg-3">
                <h6>Contact:</h6>
                <address>
                    <strong>BethanysPieShop</strong><br>
                    Rue Emile Cuvelier 123<br>
                    5000 Namur<br>
                    Belgium<br />
                    <i class="bi-telephone text-primary"></i> <a href="tel:+32479526813">(+32) 479-526813</a><br>
                    <i class="bi-envelope text-primary"></i> <a href="mailto:info@bethanyspieshop.com">info@bethanyspieshop.com</a>
                </address>
            </div>
        </div>
        <div class="text-center">&copy;@DateTime.Now.Year BethanysPieShop. All rights reserved.</div>
    </div>
</footer>

BethanysPieShopNet8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" , initial-scale="1.0" />
    <title>Bethany's Pie Shop - @ViewData["Title"]</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/litera-bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <script src="~/lib/jquery/jquery.js"></script>
</head>
<body>
    <div class="container-fluid">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary"
                 aria-label="Bethany's Pie Shop navigation header">
                <div class="container-xl">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="~/images/bethanys-pie-shop-logo_horiz-white.png" width="151" height="47"
                             class="d-inline-block align-top mb-2 mt-1" alt="Bethany's Pie Shop Logo" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <vc:category-menu></vc:category-menu>
                            <li class="nav-item">
                                <a asp-controller="About" asp-action="Index" class="nav-link">About</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a>
                            </li>

                        </ul>
                        <ul class="navbar-nav mb-2 mb-lg-0">
                            <li class="nav-item">
                                <form class="mb-3 mb-lg-0 me-lg-2" asp-controller="Pie" asp-action="Search">
                                    <div class="input-group">
                                        <input type="search" class="form-control" placeholder="Search text here" arial-label="Search pie here" value="" />
                                        <button type="Submit" class="btn btn-secondary">
                                            <i class="bi-search"></i>
                                        </button>
                                    </div>
                                </form>
                            </li>
                            <li class="nav-item dropdown">
                                <button type="button" class="btn btn-secondary dropdown-toggle"
                                        id="currencyDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                    EUR <i class="bi bi-currency-euro"></i>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="currencyDropdown">
                                    <button type="button" class="dropdown-item">
                                        USD <i class="bi bi-currency-dollar"></i>
                                    </button>
                                    <button type="button" class="dropdown-item">
                                        GBP <i class="bi bi-currency-pound"></i>
                                    </button>
                                    <button type="button" class="dropdown-item">
                                        YEN <i class="bi bi-currency-yen"></i>
                                    </button>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link me-2">
                                    <i class="fs-4 bi bi-heart text-bg-primary"></i>
                                </a>
                            </li>
                        </ul>
                        <vc:shopping-cart-summary></vc:shopping-cart-summary>

                    </div>
                </div>
            </nav>
        </header>
        @RenderBody()
        <partial name="_FooterLayout" />
    </div>


    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
</body>
</html>

BethanysPieShopNet8/Views/Shared/_PieCard.cshtml
@model Pie

<div class="col">
    <div class="card pie-card">
        <img src="@Model.ImageThumbnailUrl" class="card-img-top" alt="@Model.Name" />
        <div class="card-body pie-button">
            <h4 class="d-grid">
                <a class="btn btn-secondary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">
                    <i class="fa-solid fa-circle-plus"></i>
                    Add to cart
                </a>
            </h4>

            <div class="d-flex justify-content-between mt-2">
                <h2 class="text-start">
                    <a class="pie-link" asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">
                        @Model.Name
                    </a>
                </h2>
                <h5 class="text-nowrap">
                    @Model.Price.ToString("c")
                </h5>
            </div>
        </div>
    </div>
</div>

BethanysPieShopNet8/Views/Shared/_PieShopCarousel.cshtml
<div id="carouselImages" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="4" aria-label="Slide 5"></button>

    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/Images/carousel/carousel1.jpg" class="d-block w-100" alt="CarouselPie1">
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel/carousel2.jpg" class="d-block w-100" alt="CarouselPie2">
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel/carousel3.jpg" class="d-block w-100" alt="CarouselPie3">
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel/carousel4.jpg" class="d-block w-100" alt="CarouselPie4" />
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel/carousel5f.jpg" class="d-block w-100" alt="CarouselPie5" />
        </div>
    </div>
</div>